import type { ReactNode } from "react";

const internalNav = ["Overview", "Companies", "Business partners", "Service orders", "Billing calendar", "Invoices", "Payments", "Reports"];
const clientNav = ["Overview", "Invoices", "Payments", "Statements", "Shared documents"];

export function InternalShell({ children }: { children: ReactNode }) {
  return <div className="min-h-screen bg-[#f5f7fa] text-slate-950"><aside className="fixed inset-y-0 hidden w-64 flex-col border-r border-slate-200 bg-[#0b1b33] px-5 py-6 text-white lg:flex"><div className="mb-10"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-blue-300">L&S BUSINESS HUB</p><h1 className="mt-2 text-xl font-bold">Operations console</h1><p className="mt-2 text-xs leading-5 text-slate-400">Internal business portal</p></div><nav className="space-y-1">{internalNav.map((item, index) => <div key={item} className={`rounded-xl px-3 py-2.5 text-sm ${index === 0 ? "bg-blue-500/15 font-semibold text-blue-200" : "text-slate-400"}`}>{item}</div>)}</nav><div className="mt-auto rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-slate-400"><p className="font-semibold text-white">DEMO workspace</p><p className="mt-1">RLS-scoped staff view</p></div></aside><main className="lg:pl-64"><header className="flex items-center justify-between border-b border-slate-200 bg-white/90 px-5 py-4 backdrop-blur lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Internal portal</p><p className="mt-1 text-sm font-semibold text-slate-700">Secure staff workspace</p></div><div className="flex items-center gap-3"><span className="hidden text-right text-xs text-slate-500 sm:block">Authenticated session<br /><strong className="text-slate-800">RLS enforced</strong></span><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 text-sm font-bold text-blue-800">IA</div></div></header>{children}</main></div>;
}

export function ClientShell({ children }: { children: ReactNode }) {
  return <div className="min-h-screen bg-[#f7fbff] text-slate-950"><header className="border-b border-blue-100 bg-white px-5 py-5 lg:px-12"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-blue-600">L&S BUSINESS HUB</p><h1 className="mt-1 text-xl font-bold">Client portal</h1></div><div className="flex items-center gap-3"><span className="hidden text-right text-xs text-slate-500 sm:block">DEMO client session<br /><strong className="text-blue-700">Private organization view</strong></span><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-600 text-sm font-bold text-white">DC</div></div></div></header><div className="mx-auto flex max-w-6xl gap-8 px-5 py-5 lg:px-12"><nav className="hidden w-44 shrink-0 space-y-1 lg:block">{clientNav.map((item, index) => <div key={item} className={`rounded-xl px-3 py-2.5 text-sm ${index === 0 ? "bg-blue-600 font-semibold text-white" : "text-slate-500"}`}>{item}</div>)}</nav><main className="min-w-0 flex-1">{children}</main></div></div>;
}
